// hip_vortex_host.h - Unified host header for HIP-to-Vortex compilation
// Copyright 2024-2025 Vortex HIP Project
//
// This header provides a single include for host-side HIP code compiled for Vortex.
// It includes the HIP runtime and auto-includes generated kernel stubs if available.
//
// Usage in HIP source files:
//   #ifdef __CUDA__
//   #include "hip_runtime.h"      // Device compilation (cgeist)
//   #else
//   #include "hip_vortex_host.h"  // Host compilation (GCC/Clang)
//   #endif
//
// Link with: -lhip_vortex -lvortex

#ifndef HIP_VORTEX_HOST_H
#define HIP_VORTEX_HOST_H

// Include the full HIP-to-Vortex runtime API
#include "hip_vortex_runtime.h"

// Auto-include generated kernel stubs if they exist in the include path
// These are generated by Polygeist's ConvertGPUToVortex pass
// File: <kernel_name>_args.h (per-kernel) or kernel_stubs.h (combined)
#if __has_include("kernel_stubs.h")
#include "kernel_stubs.h"
#endif

//=============================================================================
// Helper macros for HIP code compatibility
//=============================================================================

// Host-side dim3 definition (matches device-side definition)
#ifndef __CUDA__
struct dim3 {
    unsigned int x, y, z;
    dim3(unsigned int vx = 1, unsigned int vy = 1, unsigned int vz = 1)
        : x(vx), y(vy), z(vz) {}
};
#endif

// hipLaunchKernelGGL macro for host compilation
// In host mode, this should be replaced with the generated launcher function
// Example: hipLaunchKernelGGL(vecadd_kernel, grid, block, 0, 0, a, b, c, n)
// Becomes: launch_vecadd_kernel(grid, block, a, b, c, n)
//
// If you see a compile error here, make sure to:
// 1. Include the generated kernel_stubs.h
// 2. Use the launcher function: launch_<kernel_name>(grid, block, args...)
#ifndef __CUDA__
// Override the legacy macro from hip_vortex_runtime.h with an error
// The generated launcher functions should be used instead
#undef hipLaunchKernelGGL
#define hipLaunchKernelGGL(kernel, grid, block, sharedMem, stream, ...) \
    _Pragma("GCC error \"hipLaunchKernelGGL not supported on host. Use launch_<kernel_name>() from kernel_stubs.h instead.\"")
#endif

#endif // HIP_VORTEX_HOST_H
