#!/usr/bin/env python3
"""
generate_host_stubs.py - Generate host-side stub code from kernel metadata

This script reads kernel metadata JSON files generated by Polygeist's
ConvertGPUToVortex pass and generates C++ header files that the host code
can include to properly pack kernel arguments.

The generated header provides:
1. Argument structure definitions matching Vortex's expected layout
2. Kernel registration declarations
3. Helper macros for kernel launch

Usage:
    python generate_host_stubs.py <metadata_dir> -o <output_header>
    python generate_host_stubs.py *.meta.json -o kernel_stubs.h

Example workflow:
    1. Compile device code with Polygeist (generates .meta.json files)
    2. Run this script to generate host stubs
    3. Include generated header in host code
    4. Compile host code with the stubs
"""

import json
import sys
import os
import argparse
import re
from pathlib import Path
from typing import Dict, List


def extract_base_kernel_name(full_name: str) -> str:
    """
    Extract the base kernel name from a Polygeist-generated name.

    Polygeist generates kernel variants with numeric suffixes like:
        __polygeist_launch_vecadd_kernel_kernel94263111661472
        __polygeist_launch_bitonic_sort_step

    We want to extract the original kernel name exactly as it appears in the HIP source:
        vecadd_kernel (for __polygeist_launch_vecadd_kernel_kernel12345)
        bitonic_sort_step (for __polygeist_launch_bitonic_sort_step)
        demo_kernel (for __polygeist_launch_demo_kernel)

    The extracted name must match what inject_kernel_launchers.py uses to generate
    launcher functions: launch_<kernel_name>()
    """
    base_name = None

    # Handle __polygeist_launch_ prefix
    if full_name.startswith("__polygeist_launch_"):
        name = full_name[len("__polygeist_launch_"):]

        # Try to detect and remove numeric suffix variants
        # Pattern 1: name_kernel followed by digits (e.g., demo_kernel94263)
        # This happens when kernel name ends with _kernel and Polygeist adds numbers
        match = re.match(r"(.+_kernel)\d+$", name)
        if match:
            base_name = match.group(1)
        else:
            # Pattern 2: any name followed by underscore and digits at the end
            # e.g., bitonic_sort_step_12345 -> bitonic_sort_step
            # But be careful not to strip valid parts like sort_step
            match = re.match(r"(.+?)_(\d{6,})$", name)  # Only strip if 6+ digits (Polygeist IDs)
            if match:
                base_name = match.group(1)
            else:
                # No numeric suffix, use as-is
                base_name = name

    # Handle mangled C++ names (_Z...) - legacy/fallback
    elif full_name.startswith("_Z"):
        # Try to demangle - extract function name portion
        # Simple pattern: _Z<len><name>...
        match = re.match(r"_Z(\d+)(\w+)", full_name)
        if match:
            name_len = int(match.group(1))
            base_name = match.group(2)[:name_len]
            # Mangled names have "launch_" prefix from the wrapper
            # e.g., _Z11launch_demo... -> launch_demo
            # But the kernel itself is "demo", so we strip launch_
            # and rely on the _kernel suffix being in the original name
            if base_name.startswith("launch_"):
                base_name = base_name[len("launch_"):]

    if base_name is None:
        base_name = full_name

    return base_name


def type_to_cpp(type_str: str, is_pointer: bool, for_struct: bool = False) -> str:
    """Convert metadata type string to C++ type.

    Args:
        type_str: Type string from metadata (i32, ptr, etc.)
        is_pointer: True if this is a device pointer
        for_struct: If True, returns types suitable for packed struct
                    (uses uint32_t for pointers since Vortex is RV32)
    """
    if is_pointer:
        # For struct packing, use uint32_t to match RV32 device address size
        # For function parameters, use void* for API compatibility
        return "uint32_t" if for_struct else "void*"

    type_map = {
        "i32": "int32_t",
        "i64": "int64_t",
        "f32": "float",
        "f64": "double",
        "ptr": "uint32_t" if for_struct else "void*",
    }
    return type_map.get(type_str, "uint32_t")


def generate_args_struct(kernel_name: str, args: List[Dict]) -> str:
    """Generate the kernel arguments structure."""
    base_name = extract_base_kernel_name(kernel_name)
    struct_name = f"{base_name}_args_t"

    lines = [
        f"// Argument structure for {base_name}",
        f"// Matches Vortex kernel argument layout (grid_dim, block_dim prepended by runtime)",
        f"typedef struct __attribute__((packed)) {{",
    ]

    for arg in args:
        # Use void* for pointers in the struct - vortexLaunchKernel will handle conversion
        cpp_type = type_to_cpp(arg["type"], arg.get("is_pointer", False), for_struct=False)
        comment = f"// metadata_offset={arg['offset']}, size={arg['size']}"
        if arg.get("is_pointer"):
            comment += ", device pointer (stored as host void*)"
        lines.append(f"  {cpp_type} {arg['name']};  {comment}")

    lines.append(f"}} {struct_name};")
    lines.append(f"")

    return "\n".join(lines)


def generate_kernel_metadata_array(kernel_name: str, args: List[Dict]) -> str:
    """Generate the metadata array for runtime registration.

    Note: The metadata offsets are computed for the HOST struct layout,
    where pointers are sizeof(void*) = 8 bytes on 64-bit systems.
    The device uses 4-byte pointers (RV32), but vortexLaunchKernel handles conversion.
    """
    base_name = extract_base_kernel_name(kernel_name)

    lines = [
        f"// Metadata array for {base_name}",
        f"// Offsets are for host struct (sizeof(void*) = 8 on 64-bit)",
        f"static const VortexKernelArgMeta {base_name}_metadata[] = {{",
    ]

    # Compute host struct offsets (accounting for 8-byte void* on 64-bit)
    host_offset = 0
    for arg in args:
        is_ptr = 1 if arg.get("is_pointer", False) else 0
        # On 64-bit host, pointers are 8 bytes, scalars keep their size
        host_size = 8 if arg.get("is_pointer", False) else arg["size"]
        lines.append(
            f"  {{ .offset = {host_offset}, .size = {host_size}, "
            f".is_pointer = {is_ptr} }},  // {arg['name']}"
        )
        host_offset += host_size

    lines.append("};")
    lines.append(f"#define {base_name.upper()}_NUM_ARGS {len(args)}")
    lines.append("")

    return "\n".join(lines)


def generate_launcher_function(kernel_name: str, args: List[Dict]) -> str:
    """Generate a type-safe launcher function.

    Note: Arguments are now in original order (matching kernel signature)
    after the ConvertGPUToVortex pass reorders them from Polygeist's layout.
    No runtime reordering is needed.
    """
    base_name = extract_base_kernel_name(kernel_name)
    struct_name = f"{base_name}_args_t"

    # Generate launcher function name - avoid "launch_launch_" prefix
    if base_name.startswith("launch_"):
        launcher_name = base_name  # Already has launch_ prefix
    else:
        launcher_name = f"launch_{base_name}"

    # Build parameters - args are already in original order
    params = []
    for arg in args:
        cpp_type = type_to_cpp(arg["type"], arg.get("is_pointer", False))
        if arg.get("is_pointer"):
            params.append(f"const void* {arg['name']}")
        else:
            params.append(f"{cpp_type} {arg['name']}")

    # Build argument packing - direct copy, no reordering needed
    pack_lines = []
    for arg in args:
        if arg.get("is_pointer"):
            pack_lines.append(f"  args.{arg['name']} = (void*){arg['name']};")
        else:
            pack_lines.append(f"  args.{arg['name']} = {arg['name']};")

    params_str = ", ".join(params)
    pack_str = "\n".join(pack_lines)

    lines = [
        f"// Type-safe launcher for {base_name}",
        f"// Call this from host code instead of hipLaunchKernelGGL",
        f"// Arguments are in ORIGINAL order (matching kernel signature)",
        f"inline hipError_t {launcher_name}(",
        f"    dim3 gridDim, dim3 blockDim,",
        f"    {params_str}) {{",
        f"",
        f"  {struct_name} args;",
        f"{pack_str}",
        f"",
        f"  return vortexLaunchKernel(",
        f"    \"{base_name}\",",
        f"    gridDim, blockDim,",
        f"    &args, sizeof(args),",
        f"    {base_name}_metadata, {base_name.upper()}_NUM_ARGS);",
        f"}}",
        f"",
    ]

    return "\n".join(lines)


def generate_header(kernels: Dict[str, Dict], output_name: str) -> str:
    """Generate the complete header file."""
    guard = output_name.replace(".", "_").replace("/", "_").upper()

    lines = [
        f"// Auto-generated kernel stubs for Vortex HIP runtime",
        f"// Generated by generate_host_stubs.py",
        f"// DO NOT EDIT - regenerate from metadata JSON files",
        f"//",
        f"// This header should be included AFTER hip/hip_runtime.h or hip_vortex_runtime.h",
        f"// It uses VortexKernelArgMeta and vortexLaunchKernel from that header.",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"",
        f"// Ensure hip_vortex_runtime.h was included first",
        f"#ifndef HIP_VORTEX_RUNTIME_H",
        f"#error \"kernel_stubs.h must be included after hip/hip_runtime.h or hip_vortex_runtime.h\"",
        f"#endif",
        f"",
    ]

    # Generate structures and metadata for each kernel
    seen_base_names = set()
    for kernel_name, meta in kernels.items():
        base_name = extract_base_kernel_name(kernel_name)

        # Skip if we've already generated for this base name
        if base_name in seen_base_names:
            continue
        seen_base_names.add(base_name)

        args = meta.get("arguments", [])
        if not args:
            continue

        lines.append(f"// ============================================")
        lines.append(f"// Kernel: {base_name}")
        lines.append(f"// Original: {kernel_name}")
        lines.append(f"// Arguments are in original order (reordered by ConvertGPUToVortex pass)")
        lines.append(f"// ============================================")
        lines.append("")

        lines.append(generate_args_struct(kernel_name, args))
        lines.append(generate_kernel_metadata_array(kernel_name, args))
        lines.append(generate_launcher_function(kernel_name, args))

    lines.extend([
        f"#endif // {guard}",
    ])

    return "\n".join(lines)


def load_metadata_files(paths: List[str]) -> Dict[str, Dict]:
    """Load all metadata JSON files."""
    kernels = {}

    for path in paths:
        path = Path(path)

        if path.is_dir():
            # Find all .meta.json files in directory
            json_files = list(path.glob("*.meta.json"))
        elif path.suffix == ".json" or str(path).endswith(".meta.json"):
            json_files = [path]
        else:
            # Try globbing
            json_files = list(Path(".").glob(str(path)))

        for json_file in json_files:
            try:
                with open(json_file, "r") as f:
                    meta = json.load(f)
                    kernel_name = meta.get("kernel_name", json_file.stem)
                    kernels[kernel_name] = meta
                    print(f"Loaded: {json_file} -> {kernel_name}", file=sys.stderr)
            except json.JSONDecodeError as e:
                print(f"Warning: Failed to parse {json_file}: {e}", file=sys.stderr)
            except Exception as e:
                print(f"Warning: Error loading {json_file}: {e}", file=sys.stderr)

    return kernels


def main():
    parser = argparse.ArgumentParser(
        description="Generate host stubs from kernel metadata"
    )
    parser.add_argument(
        "inputs", nargs="+",
        help="Metadata JSON files or directories containing them"
    )
    parser.add_argument(
        "-o", "--output", default="kernel_stubs.h",
        help="Output header file (default: kernel_stubs.h)"
    )

    args = parser.parse_args()

    # Load all metadata
    kernels = load_metadata_files(args.inputs)

    if not kernels:
        print("Error: No kernel metadata found", file=sys.stderr)
        return 1

    print(f"Found {len(kernels)} kernel(s)", file=sys.stderr)

    # Generate header
    header = generate_header(kernels, args.output)

    # Write output
    if args.output == "-":
        print(header)
    else:
        with open(args.output, "w") as f:
            f.write(header)
        print(f"Generated: {args.output}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
